export const industries = [
  { industry: "Advertising / Communications / Media" },
  { industry: "Agriculture" },
  { industry: "Army / Police / Fire brigade" },
  { industry: "Automotive" },
  { industry: "Aviation / Space travel" },
  { industry: "Banking & Financial Services" },
  { industry: "Biotechnology" },
  { industry: "Business services" },
  { industry: "Chemical" },
  { industry: "Construction" },
  { industry: "Culture / Art" },
  { industry: "Education / Training" },
  { industry: "Electronics" },
  { industry: "Energy / utilities" },
  { industry: "Engineering" },
  { industry: "Entertainment" },
  { industry: "Fashion" },
  { industry: "Fast Moving Consumer Goods" },
  { industry: "Food" },
  { industry: "Government / Non-profit" },
  { industry: "Heavy Industry" },
  { industry: "Hospitality / Recreation /  Travel" },
  { industry: "Housing associations / developers / property" },
  { industry: "IT" },
  { industry: "Legal" },
  { industry: "Logistics & Supply Chain" },
  { industry: "Manufacturing" },
  { industry: "Maritime" },
  { industry: "Mechanical or Industrial Engineering" },
  { industry: "Medical / Health" },
  { industry: "Oil and Gas" },
  { industry: "Other" },
  { industry: "Pharmaceutical" },
  { industry: "Printing / Graphic Arts" },
  { industry: "Recruitment" },
  { industry: "Retail / Wholesale" },
  { industry: "Sport" },
  { industry: "Telecommunications" },
];

export const inds = [
  { industry: "Accounting", enum: "ACCOUNTING" },
  { industry: "Academic", enum: "ACADEMIC" },
  { industry: "Advertising", enum: "ADVERTISING" },
  { industry: "Aerospace", enum: "AEROSPACE" },
  { industry: "Agriculture", enum: "AGRICULTURE" },
  { industry: "Arts culture", enum: "ARTS_CULTURE" },
  { industry: "Automotive", enum: "AUTOMOTIVE" },
  { industry: "Aviation", enum: "AVIATION" },
  { industry: "Banking", enum: "BANKING" },
  { industry: "Building construction", enum: "BUILDING_CONSTRUCTION" },
  {
    industry: "Charity and not for profit",
    enum: "CHARITY_AND_NOT_FOR_PROFIT",
  },
  { industry: "Communications", enum: "COMMUNICATIONS" },
  { industry: "Education", enum: "EDUCATION" },
  { industry: "Energy", enum: "ENERGY" },
  { industry: "Engineering", enum: "ENGINEERING" },
  { industry: "Entertainment", enum: "ENTERTAINMENT" },
  { industry: "Facility management", enum: "FACILITY_MANAGEMENT" },
  { industry: "Fashion", enum: "FASHION" },
  {
    industry: "Fast moving consumer goods",
    enum: "FAST_MOVING_CONSUMER_GOODS",
  },
  { industry: "Finance", enum: "FINANCE" },
  { industry: "Food", enum: "FOOD" },
  { industry: "Generic", enum: "GENERIC" },
  {
    industry: "Goverment and public sector",
    enum: "GOVERNMENT_AND_PUBLIC_SECTOR",
  },
  { industry: "Health and safety", enum: "HEALTH_AND_SAFETY" },
  { industry: "Healthcare", enum: "HEALTHCARE" },
  { industry: "Hospitality", enum: "HOSPITALITY" },
  { industry: "Information technology", enum: "INFORMATION_TECHNOLOGY" },
  { industry: "Insurance", enum: "INSURANCE" },
  // { industry: "Insurance", enum: "INSURANCE" },
  { industry: "Legal", enum: "LEGAL" },
  { industry: "Leisure and sport", enum: "LEISURE_AND_SPORT" },
  { industry: "Logistics supply chain", enum: "LOGISTICS_SUPPLY_CHAIN" },
  { industry: "Manufactoring", enum: "MANUFACTURING" },
  { industry: "Maritime", enum: "MARITIME" },
  { industry: "Media", enum: "MEDIA" },
  { industry: "Multilingual", enum: "MULTILINGUAL" },
  { industry: "Pharmaceuticals", enum: "PHARMACEUTICALS" },
  { industry: "Property and housing", enum: "PROPERTY_AND_HOUSING" },
  { industry: "Real estate", enum: "REAL_ESTATE" },
  { industry: "Recrutment", enum: "RECRUITMENT" },
  { industry: "Retail", enum: "RETAIL" },
  { industry: "Science reserch", enum: "SCIENCE_RESEARCH" },
  { industry: "Sustainability", enum: "SUSTAINABILITY" },
  { industry: "Telecommunications", enum: "TELECOMMUNICATIONS" },
  { industry: "Transport and rail", enum: "TRANSPORT_AND_RAIL" },
  { industry: "Travel and tourism", enum: "TRAVEL_AND_TOURISM" },
];

export const employmentTypes = [
  { type: "Fixed term", enum: "fixed_term" },
  {
    type: "Fixed term with option for permanent",
    enum: "fixed_term_with_option_for_permanent",
  },
  { type: "Freelance", enum: "freelance" },
  { type: "Internship", enum: "internship" },
  { type: "Temporary", enum: "temporary" },
  { type: "Permanent", enum: "permanent" },
  { type: "Traineeship", enum: "traineeship" },
];

export const senioritis = [
  { seniority: "Student/Trainee", enum: "TRAINEE" },
  { seniority: "Entry level/Graduate", enum: "GRADUATE" },
  { seniority: "Mid-Senior level", enum: "MID_OR_SENIOR" },
  { seniority: "Manager", enum: "MANAGER" },
  { seniority: "Executive/Director", enum: "EXECUTIVE" },
];

export const currencies = [
  { currency: "€", enum: "EUR" },
  { currency: "£", enum: "GBP" },
  { currency: "$", enum: "USD" },
];

export const periods = [
  { period: "Hourly", enum: "hourly" },
  { period: "Daily", enum: "daily" },
  { period: "Weekly", enum: "weekly" },
  { period: "Monthly", enum: "monthly" },
  { period: "Yearly", enum: "yearly" },
];

export enum CheckoutStep {
  Address = 1,
  Shipping,
  Payment,
  Review,
  PaymentConfirm,
}

export const educationLvl = [
  { value: "Bachelor / Graduate", enum: "BACHELOR" },
  { value: "GCSE / A-Level / Highschool / GED", enum: "GCSE" },
  { value: "Master / Post-Graduate / PhD", enum: "MASTER" },
  { value: "Vocational / Diploma / Associates degree", enum: "VOCATIONAL" },
];
